stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo clippy -- Dwarnings
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo clippy -- Dwarnings
    - cargo build --verbose
    - cargo test --verbose
