stages:
  - build

lint-and-test:
  stage: build
  image: nexus.ex.c-lab.ee:8003/rust-builder
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -- -Dwarnings
    - cargo build --verbose
    - cargo test --verbose
  cache:
    key: sdl-cargo-target
    paths:
      - target

build-x86-64bit-windows-release:
  stage: build
  needs: ["lint-and-test"]
  image: nexus.ex.c-lab.ee:8003/rust-builder
  script:
    - cargo deb --no-build --target x86_64-unknown-linux-gnu -p sdl-parser-export
    - cargo build --release --target x86_64-pc-windows-gnu
  cache:
    key: sdl-cargo-target
    paths:
      - target

build-x86-64bit-linux-release:
  stage: build
  needs: ["lint-and-test"]
  image: nexus.ex.c-lab.ee:8003/rust-builder
  script:
    - cargo build --release --target x86_64-unknown-linux-gnu
  cache:
    key: sdl-cargo-target
    paths:
      - target

build-arm-64bit-linux-release:
  stage: build
  needs: ["lint-and-test"]
  image: nexus.ex.c-lab.ee:8003/rust-builder
  script:
    - cargo build --release --target aarch64-unknown-linux-gnu
    - cargo deb --no-build --target aarch64-unknown-linux-gnu -p sdl-parser-export
  cache:
    key: sdl-cargo-target
    paths:
      - target
